/*  =========================================================================
    zm-device - generated layer of public API

    Copyright (c) the Contributors as noted in the AUTHORS file.  This file is part
    of zmon.it, the fast and scalable monitoring system.                           
                                                                                   
    This Source Code Form is subject to the terms of the Mozilla Public License, v.
    2.0. If a copy of the MPL was not distributed with this file, You can obtain   
    one at http://mozilla.org/MPL/2.0/.                                            

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef ZM_DEVICE_LIBRARY_H_INCLUDED
#define ZM_DEVICE_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <malamute.h>
#include <zmproto.h>

//  ZM_DEVICE version macros for compile-time API detection
#define ZM_DEVICE_VERSION_MAJOR 1
#define ZM_DEVICE_VERSION_MINOR 0
#define ZM_DEVICE_VERSION_PATCH 0

#define ZM_DEVICE_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ZM_DEVICE_VERSION \
    ZM_DEVICE_MAKE_VERSION(ZM_DEVICE_VERSION_MAJOR, ZM_DEVICE_VERSION_MINOR, ZM_DEVICE_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined ZM_DEVICE_STATIC
#       define ZM_DEVICE_EXPORT
#   elif defined ZM_DEVICE_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define ZM_DEVICE_EXPORT __declspec(dllexport)
#       else
#           define ZM_DEVICE_EXPORT
#       endif
#   elif defined ZM_DEVICE_EXPORTS
#       define ZM_DEVICE_EXPORT __declspec(dllexport)
#   else
#       define ZM_DEVICE_EXPORT __declspec(dllimport)
#   endif
#   define ZM_DEVICE_PRIVATE
#else
#   define ZM_DEVICE_EXPORT
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define ZM_DEVICE_PRIVATE __attribute__ ((visibility ("hidden")))
#   else
#       define ZM_DEVICE_PRIVATE
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  ZM_DEVICE_BUILD_DRAFT_API
#define ZM_DEVICE_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef ZM_DEVICE_BUILD_DRAFT_API
typedef struct _list_t list_t;
#define LIST_T_DEFINED
#endif // ZM_DEVICE_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef ZM_DEVICE_BUILD_DRAFT_API
#include "list.h"
#endif // ZM_DEVICE_BUILD_DRAFT_API

#ifdef ZM_DEVICE_BUILD_DRAFT_API
//  Self test for private classes
ZM_DEVICE_EXPORT void
    zm_device_private_selftest (bool verbose);
#endif // ZM_DEVICE_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
